# Dockerfile.frontend
FROM node:16

# Set working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy project files
COPY . .

# Build the Vue.js application
#RUN npm run build

# Expose port
EXPOSE 8080

# Command to run the application
CMD ["npm", "run", "serve"]
