version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: laravel_backend
    restart: unless-stopped
    volumes:
      - ./app:/var/www
      # Ensure the database directory is shared with the container
      - ./app/database:/var/www/database 
    ports:
      - "9000:9000"  # Laravel backend on port 9000
    networks:
      - app_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: vue_frontend
    restart: unless-stopped
    ports:
      - "8080:8080"  # Vue.js frontend on port 8080
    networks:
      - app_network

  cron:
    build:
      context: .
      dockerfile: Dockerfile.cron
    container_name: laravel_cron
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
