services:
  laravel_sail_app_backend:
    build:
      context: ./vendor/laravel/sail/runtimes/8.3
      dockerfile: Dockerfile
      args:
        WWWGROUP: "1000"
    environment:
      IGNITION_LOCAL_SITES_PATH: /var/www/html
      LARAVEL_SAIL: "1"
      XDEBUG_CONFIG: client_host=host.docker.internal
      XDEBUG_MODE: "off"
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
    extra_hosts:
      - host.docker.internal=host-gateway
    image: sail-8.3/app
    container_name: main_container_PROD
    networks:
      - sail
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - vue_frontend

  cron-schedulework:
      build:
        context: ./
        dockerfile: Dockerfile.cron
      command: php /var/www/html/artisan schedule:work
      volumes:
        - .:/var/www/html
      container_name: background_cron_schedule_worker
      networks:
        - sail  

  vue_frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    container_name: vue_frontend
    restart: unless-stopped
    ports:
      - "5173:5173" 
    networks:
      - sail
    command: npm run dev -- --host 

networks:
  sail:
    driver: bridge
  app-network:
    driver: bridge
