version: '3.8'
services:
  laravel.test:
    build:
      context: ./vendor/laravel/sail/runtimes/8.3
      dockerfile: Dockerfile
      args:
        WWWGROUP: "1000"
    environment:
      IGNITION_LOCAL_SITES_PATH: /var/www/html
      LARAVEL_SAIL: "1"
      XDEBUG_CONFIG: client_host=host.docker.internal
      XDEBUG_MODE: "off"
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
    extra_hosts:
      - host.docker.internal=host-gateway
    image: sail-8.3/app
    networks:
      - sail
    ports:
      - "80:80"
      - "5174:5174"
    volumes:
      - .:/var/www/html
  cron-schedulework:
    build:
      context: ./
      dockerfile: Dockerfile.cron
    command: php /var/www/html/artisan schedule:work
    volumes:
      - .:/var/www/html
    networks:
      - sail
networks:
  sail:
    driver: bridge
